In [19]:
import matplotlib.pyplot as plt
import numpy as np

In [20]:
def func(t,y):
  return y - t**2 + 1

In [21]:
def runge_kutta_2(Ti,Tf,y0,h,function):
  N = int(np.ceil((Tf - Ti)/h))
  t = np.zeros(N + 1)
  y = np.zeros(N + 1)
  y[0] = y0
  t[0] = Ti
  for i in range(N):
    y[i + 1] = y[i] + h*function(t[i] + h/2, y[i] + (h/2)*function(t[i],y[i]))
    t[i + 1] = t[i] + h
  return t,y;

In [22]:
runge_kutta_2(0,2,0.5,0.2,func)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]),
 array([0.5       , 0.828     , 1.21136   , 1.6446592 , 2.12128422,
        2.63316675, 3.17046344, 3.7211654 , 4.27062178, 4.80095857,
        5.29036946]))

In [23]:
def runge_kutta_4(Ti,Tf,y0,h,function):
  N = int(np.ceil((Tf - Ti)/h))
  t = np.zeros(N + 1)
  y = np.zeros(N + 1)
  y[0] = y0
  t[0] = Ti
  for i in range(N):
    k1 = h*function(t[i],y[i])
    k2 = h*function(t[i] + h/2, y[i] + (1/2)*k1)
    k3 = h*function(t[i] + h/2, y[i] + (1/2)*k2)
    t[i + 1] = t[i] + h
    k4 = h*function(t[i + 1],y[i] + k3)
    y[i + 1] = y[i] + (1/6)*(k1 + 2*k2 + 2*k3 + k4)
  return t,y

In [24]:
runge_kutta_4(0,2,0.5,0.2,func)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]),
 array([0.5       , 0.82929333, 1.21407621, 1.64892202, 2.12720268,
        2.64082269, 3.17989417, 3.73234007, 4.2834095 , 4.81508569,
        5.305363  ]))

In [25]:
h = [0.5]

In [26]:
def aprox_plot(Ti,Tf,y0,h,function,method):
    t,y = rungen_kutta_2